name: Wheel Builder
permissions:
  contents: write
defaults:
  run:
    shell: bash
on:
  workflow_dispatch:
    inputs:
      version:
        description: The version to build
  schedule:
    - cron: '37 12 * * *'
  push:
  pull_request:
    paths:
      - .github/workflows/wheel-builder.yml
      - .github/requirements/**
      - pyproject.toml
      - vectors/pyproject.toml

jobs:
  windows:
    runs-on: windows-11-arm
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: 'windows-11-arm'
    steps:

      - run: echo "VCPKG_ROOT=$env:VCPKG_INSTALLATION_ROOT" | Out-File -FilePath $env:GITHUB_ENV -Append
        
      - run: vcpkg install openssl:arm64-windows-static-md
        
      - uses: actions-rust-lang/setup-rust-toolchain@v1

      - uses: actions/setup-python@v5
        with:
          python-version: '3.X'

      - name: Upgrade pip, wheel, etc
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install --upgrade wheel
          python3 -m pip install --upgrade setuptools

      - name: download latest crypto version
        run: |
          git clone https://github.com/pyca/cryptography.git
          cd cryptography
          export latest_release=$(git tag --list | sort -Vr | head -n1)
          git checkout "${latest_release}"

      - name: Install cibuildwheel
        run: |
          python3 -m pip install cibuildwheel

      - name: Build wheels
        run: |
          cd cryptography
          export CIBW_PLATFORM="windows"
          export CIBW_ARCHS_WINDOWS="ARM64"
          export CIBW_BUILD="cp39-*"
          python3 -m cibuildwheel --output-dir wheelhouse

      - name: Install wheel
        run: |
          ls -l cryptography/wheelhouse/
          python3 -m pip install cryptography/wheelhouse/*.whl

      - name: Print the OpenSSL we built and linked against
        run: |
            python3 -c "from cryptography.hazmat.backends.openssl.backend import backend;print('Loaded: ' + backend.openssl_version_text());print('Linked Against: ' + backend._ffi.string(backend._lib.OPENSSL_VERSION_TEXT).decode('ascii'))"
          
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: "cryptography-${{ github.event.inputs.version }}-${{ matrix.WINDOWS.WINDOWS }}-${{ matrix.PYTHON.VERSION }}"
          path: cryptography/wheelhouse/*.whl

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          automatic_release_tag: "latest"
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          draft: false
          title: "Wheel Build"
          files: |
            cryptography/wheelhouse/*.whl
